# Travis yml file inspired by scikit-bio
sudo: false
language: python
env:
  - PYVERSION=3.7.2 USE_CYTHON=TRUE MAKE_DOC=TRUE
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda info -a
install:
  - conda env create -q -n test-env --file resources/environment.yml
  - conda install --yes -n test-env cython
  - source activate test-env  
  - pip install -e .
script:
  - source activate test-env
  - nosetests -v tests --with-coverage --cover-package=TesasSemble 
after_success:
  - coveralls
notifications:
  webhooks:
    on_success: change
    on_failure: always
